### ISSUE TITLE
Esp8266 wdt reset 

### ISSUE THREAD

**Issue by sashahn** [arduino12/rdm6300#2]
Hi, actually my issue is not directly connected with RDM6300 library...the issue is if a card is in slot continuously esp8266 will crash- wdt....so, after investing the issue, my conclusion is that Software serial cause it .
What I should do to switch Software serial to Hardware serial? 
OTA is used for firmware upload.
Thank you

**Comment by arduino12** [comment]
Hi,

I'll add an optional argument to the constructor so the user can supply his favorite serial device (hardware or software) tonight.

Thanks for noticing..!

**Comment by sashahn** [comment]
Thank you for prompt reply.
RDM6300 library works flawless with ESP32-Hardware serial UART2 for 9 days/nights. ID card is in  the slot almost all the time, few times card is pulled out and back just for tests - no issues appears.
I assume that tag presence for the long time  triggers large burst of interrupts - Software Serial Locks the  esp8266 no time for yielding  - watch dog is not fed  which cause wdt resets.
Oh almost to forgot:
This issue happens only when ESP8266 use WiFI and Serial software.
Best regards

**Comment by arduino12** [comment]
Hi,

I have added esp8266 hardware uart support with an [example](https://github.com/arduino12/rdm6300/blob/master/examples/esp8266_hardware_uart/esp8266_hardware_uart.ino)!
Just finish testing with all of my boards: esp32, esp8266, avr..

Let me know if it stops your wdt reset problem :)
