### ISSUE TITLE
Voltage divider is not needed for 3.3V microcontrollers

### ISSUE THREAD

**Issue by gutierrezps** [arduino12/rdm6300#4]
I measured the voltage on pins TX and RX of two RDM6300 modules I've got, and they're around 3.3V, not 5V. So the voltage divider is not necessary to connect the RDM6300 to ESP8266.

**Comment by gutierrezps** [comment]
Since you're possibly going to update the schematics, I would like to suggest adding the detection LED that can be driven by the module, like this:

![RDM6300 schematic with LED](https://user-images.githubusercontent.com/5178460/59034939-9aedb700-8842-11e9-8232-6ba4187b4b64.png)

Where the pin numbering goes like this:

![RDM6300 footprint pins numbering](https://user-images.githubusercontent.com/5178460/59035465-bc9b6e00-8843-11e9-8a06-2189283e392a.png)

**Comment by arduino12** [comment]
Hi,

Sorry for my late reply,
I tested my RDM6300 module as well- and you're right - there's no need for an external resistor divider!

I'd like to attach your schematics, if you can add the following changes:
1. PIN10 isn't a 5V, but a reverse polarity protection via a diode.
2. Rename LED to CARD_DETECTED_LED and add a 1K resistor between 5V and the LED.

Thanks,
Arad

**Comment by gutierrezps** [comment]
I think your fritzing schematics are more intuitive for newcomers, but if you really wish to include my schematics:

1. ~Do you have a source for that? Because in a lot of places is said both pins 4 and 10 are +5V inputs.~ Okay, I checked the bottom side of the module and there's indeed a [SS14 schottky diode](https://www.vishay.com/docs/88746/ss12.pdf) between pins 10 and 4. How do you think pin 10 should be labelled then? Both pins can still be used to power the module anyway.
2. a) I think "CARD_DETECTED_LED" is very verbose (compared to the other pins), and again this pin is simply known as LED. What I can do is add a bar over the name to indicate it's active low, following [KiCAD Library Convention's Guideline S4.7](http://kicad-pcb.org/libraries/klc/S4.7/). b) ~Indeed, I was using it without a resistor, but the RDM630 datasheet (the "original" module) uses the pin to drive a PNP transistor.~ I added a 470R resistor here, and the LED blinking became pretty dim. I'll plug an oscilloscope later to measure the current and pulse width to see if it's safe to use without the resistor.

Sources:
<https://www.itead.cc/wiki/RDM6300>
<http://wiki.seeedstudio.com/125Khz_RFID_module-UART/>
<https://github.com/SeeedDocument/125Khz_RFID_module-UART/raw/master/res/RDM630-Spec.pdf>
<https://datasheetspdf.com/pdf/788733/RDM/RDM630/1>

**Comment by arduino12** [comment]
Hi,

OK, let me know about the LED current,
When you're done, please attach the final schematics here and I'll close the issue :)

Arad
