### ISSUE TITLE
Add support to AltSoftSerial

### ISSUE THREAD

**Issue by gutierrezps** [arduino12/rdm6300#6]
Hi again. After facing issue #5 on ESP8266, my workaround was to move the RDM6300 to an Arduino Nano (that I'm already using for other functions) that communicates with the ESP through I2C. And to my surprise, while a tag was being read, the Arduino returned garbage on the I2C, and sometimes even locked the bus by keeping the SDA line low.

So I plugged a logic analyzer and there it was: the I2C transaction was becoming corrupt if data was being sent by the RFID reader.

Here's a proper I2C transaction between the Arduino and the ESP:

![Proper I2C transaction](https://user-images.githubusercontent.com/5178460/59557220-cb53f480-8faa-11e9-8032-f8065f1b950b.png)

And here's the I2C transaction being corrupted while the RFID is sending the tag data.

![Corrupted I2C transaction](https://user-images.githubusercontent.com/5178460/59557230-09511880-8fab-11e9-848e-4c9d975a330e.png)

Notice that the I2C transaction is fragmented, and also the bus is locked up after that. After searching about problems with SoftwareSerial, I came across [PaulStoffregen/AltSoftSerial library](https://github.com/PaulStoffregen/AltSoftSerial), replaced it on RDM6300 library, and the I2C problems vanished. The downside was that only pin 8 could be used for Serial RX, but it wasn't a problem for me.

That said, what do you think about adding support to [AltSoftSerial library](https://github.com/PaulStoffregen/AltSoftSerial) on ATmega328 based Arduinos (Uno, Nano, Pro Mini, etc)?

**Comment by arduino12** [comment]
Hi,

Amazing work! PulseView is the best!
I didn't see you send a PR for this issue, so I'll try to add AltSoftSerial support in the next week...

Hope [plerup/espsoftwareserial#100](https://github.com/plerup/espsoftwareserial/issues/100) fix will be available soon,
Arad

**Comment by gutierrezps** [comment]
Thanks! I've opened the PR #7 right now, take a look and see if it's okay.
