### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bkensey** [arduino12/rdm6300#8]
This is such a great library for handling RDM 6300 input. I've been trying unsuccessfully to get my reader working with a Particle Photon for longer than I care to admit, and this library was a great help. I noticed that you didn't specify a license for this code, and I was wondering if it was available for use. I ask because the project I want to use this for is an access control system for my city's non-profit makerspace and I want to make sure things are done by the book.

Thanks!

**Comment by arduino12** [comment]
Hi,

I have just licensed the repo with GNU GPL V3.

Thanks for notice and good luck with your Makerspace,
Arad
